import Link from "next/link";
import Image from "next/image";
import TeamMemberContent from "./TeamMemberContent";

const teamData: Record<string, { name: string; role: string; exp: string; bio: string; education: string[]; experience: string[]; certificates: string[]; specialization: string[]; photo: string; reviews: { text: string; author: string }[]; articles: { title: string; date: string }[]; cases: { title: string; result: string }[] }> = {
  petrenko: { name: "Олександр Петренко", role: "Керуючий партнер", exp: "15+ років", bio: "Досвідчений адвокат з понад 15-річним стажем у корпоративному праві.", education: ["КНУ ім. Т. Шевченка (2009)", "Національна академія прокуратури (2011)"], experience: ["Юридична фірма «Коваль і Партнери» (2009-2015)", "Юридична компанія (2015-теперішній час)"], certificates: ["Свідоцтво адвоката", "Сертифікат IBA"], specialization: ["Корпоративне право", "M&A", "Due diligence"], photo: "https://i.pravatar.cc/400?img=68", reviews: [{ text: "Олександр вирішив наш корпоративний спір за 3 місяці. Рекомендую!", author: "Тетяна К." }, { text: "Професійний підхід на найвищому рівні.", author: "Максим Д." }], articles: [{ title: "Як захистити бізнес від рейдерства", date: "15 листопада 2024" }, { title: "Корпоративні спори: що потрібно знати", date: "1 жовтня 2024" }], cases: [{ title: "M&A операція", result: "Угоду закрито успішно" }, { title: "Корпоративний спір", result: "Мирова угода" }] },
  kovalenko: { name: "Марія Коваленко", role: "Старший адвокат", exp: "12+ років", bio: "Адвокат з великим досвідом у сімейному праві.", education: ["НУ «Київська політехніка» (2012)"], experience: ["Адвокатське об'єднання «Право» (2012-2018)", "Юридична компанія (2018-теперішній час)"], certificates: ["Свідоцтво адвоката"], specialization: ["Сімейне право", "Цивільні спори"], photo: "https://i.pravatar.cc/400?img=45", reviews: [{ text: "Марія дуже чутливо підійшла до моєї сімейної справи.", author: "Олена В." }], articles: [{ title: "Як захистити права дитини при розлученні", date: "20 листопада 2024" }], cases: [{ title: "Поділ майна", result: "Стягнуто 1.8 млн грн" }] },
  shevchenko: { name: "Дмитро Шевченко", role: "Адвокат", exp: "8+ років", bio: "Спеціаліст у кримінальному праві.", education: ["ХНУ ім. В.Н. Каразіна (2016)"], experience: ["Слідчий ОВС (2016-2019)", "Адвокат (2019-теперішній час)"], certificates: ["Свідоцтво адвоката"], specialization: ["Кримінальне право", "Захист"], photo: "https://i.pravatar.cc/400?img=53", reviews: [{ text: "Дмитро врятував мене від серйозних неприємностей.", author: "Андрій С." }], articles: [{ title: "Ваши права при затриманні", date: "5 листопада 2024" }], cases: [{ title: "Захист за шахрайство", result: "Провадження закрито" }] },
  melnyk: { name: "Анна Мельник", role: "Юрист", exp: "5+ років", bio: "Юрист у податковому праві.", education: ["КНЕУ (2019)"], experience: ["Юридична компанія (2019-теперішній час)"], certificates: ["Сертифікат податкового консультанта"], specialization: ["Податкове право"], photo: "https://i.pravatar.cc/400?img=47", reviews: [{ text: "Анна зменшила наш податковий штраф на 82%.", author: "Товариство «Будівельник»" }], articles: [{ title: "Як оскаржити податкове рішення", date: "10 жовтня 2024" }], cases: [{ title: "Оскарження донарахування", result: "82% штрафу зменшено" }] },
  bondarenko: { name: "Ігор Бондаренко", role: "Адвокат", exp: "10+ років", bio: "Адвокат у сфері нерухомості.", education: ["ОНУ (2014)"], experience: ["Юридична фірма (2014-2020)", "Юридична компанія (2020-теперішній час)"], certificates: ["Свідоцтво адвоката"], specialization: ["Нерухомість", "Земельне право"], photo: "https://i.pravatar.cc/400?img=59", reviews: [{ text: "Ігор стягнув компенсацію від забудовника.", author: "Олексій П." }], articles: [{ title: "Як захиститися від недобросовісного забудовника", date: "1 листопада 2024" }], cases: [{ title: "Спор із забудовником", result: "Стягнуто 2.4 млн грн" }] },
  tkachenko: { name: "Катерина Ткаченко", role: "Юрист", exp: "4+ роки", bio: "Юрист у IT праві.", education: ["КНУ ім. Т. Шевченка (2020)"], experience: ["Юридична компанія (2020-теперішній час)"], certificates: ["Сертифікат з IT права"], specialization: ["IT право", "Міграційне право"], photo: "https://i.pravatar.cc/400?img=44", reviews: [{ text: "Катерина допомогла з оформленням дозволів для нашої IT-компанії.", author: "Студія «Код»" }], articles: [{ title: "Юридичні аспекти IT-бізнесу", date: "20 жовтня 2024" }], cases: [{ title: "IT-спір", result: "Договір переглянуто на користь клієнта" }] },
};

export function generateStaticParams() { return Object.keys(teamData).map((slug) => ({ slug })); }

export default async function TeamMemberPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const m = teamData[slug] || teamData.petrenko;

  return <TeamMemberContent m={m} />;
}
